package uam.rmb.gramaticaslibresdecontexto;

import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author RaulMb
 */
public class Ventana extends javax.swing.JFrame {

	private Lectura lectura;
	private Derivacion derivacion;
	private int tamMaxCabeza;
	private ArrayList<Regla> reglas;
	private ArrayList<String> soluciones;
	private String rutaArchivo;

	/**
	 * Creates new form Ventana
	 */
	public Ventana() {
		initComponents();
		lectura = new Lectura();
		derivacion = new Derivacion();
		soluciones = new ArrayList<>();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      buttonGroup1 = new javax.swing.ButtonGroup();
      background = new javax.swing.JPanel();
      jPanel2 = new javax.swing.JPanel();
      jPanel3 = new javax.swing.JPanel();
      jPanel4 = new javax.swing.JPanel();
      jPanel5 = new javax.swing.JPanel();
      jPanel6 = new javax.swing.JPanel();
      jPanel8 = new javax.swing.JPanel();
      jLabel2 = new javax.swing.JLabel();
      jPanel9 = new javax.swing.JPanel();
      jPanel12 = new javax.swing.JPanel();
      jScrollPane1 = new javax.swing.JScrollPane();
      jtaReglas = new javax.swing.JTextArea();
      jPanel13 = new javax.swing.JPanel();
      jPanel14 = new javax.swing.JPanel();
      jPanel15 = new javax.swing.JPanel();
      jPanel1 = new javax.swing.JPanel();
      jLabel3 = new javax.swing.JLabel();
      jtfCadena = new javax.swing.JTextField();
      jPanel16 = new javax.swing.JPanel();
      btnDerivar = new javax.swing.JButton();
      jPanel17 = new javax.swing.JPanel();
      jrbDer = new javax.swing.JRadioButton();
      jrbIzq = new javax.swing.JRadioButton();
      jPanel7 = new javax.swing.JPanel();
      jPanel10 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      jPanel11 = new javax.swing.JPanel();
      jScrollPane2 = new javax.swing.JScrollPane();
      jtaResultado = new javax.swing.JTextArea();
      jMenuBar1 = new javax.swing.JMenuBar();
      jMenu1 = new javax.swing.JMenu();
      Abrir = new javax.swing.JMenuItem();
      GuardarCambios = new javax.swing.JMenuItem();
      Salir = new javax.swing.JMenuItem();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Derivaciones");
      setPreferredSize(new java.awt.Dimension(800, 600));

      background.setLayout(new java.awt.BorderLayout());

      jPanel2.setMinimumSize(new java.awt.Dimension(100, 20));
      jPanel2.setPreferredSize(new java.awt.Dimension(20, 280));

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 100, Short.MAX_VALUE)
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 559, Short.MAX_VALUE)
      );

      background.add(jPanel2, java.awt.BorderLayout.LINE_START);

      jPanel3.setPreferredSize(new java.awt.Dimension(20, 360));

      javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 20, Short.MAX_VALUE)
      );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 559, Short.MAX_VALUE)
      );

      background.add(jPanel3, java.awt.BorderLayout.LINE_END);

      jPanel4.setPreferredSize(new java.awt.Dimension(700, 20));

      javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
      jPanel4.setLayout(jPanel4Layout);
      jPanel4Layout.setHorizontalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 800, Short.MAX_VALUE)
      );
      jPanel4Layout.setVerticalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 20, Short.MAX_VALUE)
      );

      background.add(jPanel4, java.awt.BorderLayout.PAGE_END);

      jPanel5.setLayout(new java.awt.BorderLayout());

      jPanel6.setPreferredSize(new java.awt.Dimension(760, 300));
      jPanel6.setLayout(new java.awt.BorderLayout());

      jPanel8.setMinimumSize(new java.awt.Dimension(100, 50));
      jPanel8.setPreferredSize(new java.awt.Dimension(760, 30));

      jLabel2.setText("REGLAS PRESENTES EN LA GRAMATICA");

      javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
      jPanel8.setLayout(jPanel8Layout);
      jPanel8Layout.setHorizontalGroup(
         jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel8Layout.createSequentialGroup()
            .addComponent(jLabel2)
            .addGap(0, 529, Short.MAX_VALUE))
      );
      jPanel8Layout.setVerticalGroup(
         jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel8Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel2)
            .addContainerGap(29, Short.MAX_VALUE))
      );

      jPanel6.add(jPanel8, java.awt.BorderLayout.PAGE_START);

      jPanel9.setLayout(new java.awt.BorderLayout());

      jPanel12.setPreferredSize(new java.awt.Dimension(400, 275));
      jPanel12.setLayout(new java.awt.BorderLayout());

      jtaReglas.setColumns(20);
      jtaReglas.setRows(5);
      jScrollPane1.setViewportView(jtaReglas);

      jPanel12.add(jScrollPane1, java.awt.BorderLayout.CENTER);

      jPanel9.add(jPanel12, java.awt.BorderLayout.LINE_START);

      jPanel13.setLayout(new java.awt.BorderLayout());

      jPanel14.setPreferredSize(new java.awt.Dimension(20, 275));

      javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
      jPanel14.setLayout(jPanel14Layout);
      jPanel14Layout.setHorizontalGroup(
         jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 20, Short.MAX_VALUE)
      );
      jPanel14Layout.setVerticalGroup(
         jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 270, Short.MAX_VALUE)
      );

      jPanel13.add(jPanel14, java.awt.BorderLayout.LINE_START);

      jPanel15.setLayout(new java.awt.BorderLayout());

      jPanel1.setPreferredSize(new java.awt.Dimension(340, 70));

      jLabel3.setText("CADENA A DERIVAR");

      jtfCadena.setPreferredSize(new java.awt.Dimension(300, 30));

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
               .addComponent(jtfCadena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(0, 40, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jtfCadena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 19, Short.MAX_VALUE))
      );

      jPanel15.add(jPanel1, java.awt.BorderLayout.PAGE_START);

      jPanel16.setPreferredSize(new java.awt.Dimension(340, 70));
      jPanel16.setLayout(new java.awt.BorderLayout());

      btnDerivar.setText("INICIAR DERIVACION");
      btnDerivar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnDerivarActionPerformed(evt);
         }
      });
      jPanel16.add(btnDerivar, java.awt.BorderLayout.CENTER);

      jPanel15.add(jPanel16, java.awt.BorderLayout.PAGE_END);

      jPanel17.setLayout(new java.awt.BorderLayout());

      buttonGroup1.add(jrbDer);
      jrbDer.setText("DERECHA");
      jPanel17.add(jrbDer, java.awt.BorderLayout.LINE_END);

      buttonGroup1.add(jrbIzq);
      jrbIzq.setSelected(true);
      jrbIzq.setText("IZQUIERDA");
      jPanel17.add(jrbIzq, java.awt.BorderLayout.LINE_START);

      jPanel15.add(jPanel17, java.awt.BorderLayout.CENTER);

      jPanel13.add(jPanel15, java.awt.BorderLayout.CENTER);

      jPanel9.add(jPanel13, java.awt.BorderLayout.CENTER);

      jPanel6.add(jPanel9, java.awt.BorderLayout.CENTER);

      jPanel5.add(jPanel6, java.awt.BorderLayout.PAGE_START);

      jPanel7.setLayout(new java.awt.BorderLayout());

      jPanel10.setPreferredSize(new java.awt.Dimension(760, 50));

      jLabel1.setText("RESULTADO DE LA DERIVACION");

      javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
      jPanel10.setLayout(jPanel10Layout);
      jPanel10Layout.setHorizontalGroup(
         jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel10Layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addGap(0, 572, Short.MAX_VALUE))
      );
      jPanel10Layout.setVerticalGroup(
         jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
            .addContainerGap(29, Short.MAX_VALUE)
            .addComponent(jLabel1)
            .addContainerGap())
      );

      jPanel7.add(jPanel10, java.awt.BorderLayout.PAGE_START);

      jPanel11.setLayout(new java.awt.BorderLayout());

      jtaResultado.setEditable(false);
      jtaResultado.setColumns(20);
      jtaResultado.setRows(5);
      jScrollPane2.setViewportView(jtaResultado);

      jPanel11.add(jScrollPane2, java.awt.BorderLayout.CENTER);

      jPanel7.add(jPanel11, java.awt.BorderLayout.CENTER);

      jPanel5.add(jPanel7, java.awt.BorderLayout.CENTER);

      background.add(jPanel5, java.awt.BorderLayout.CENTER);

      getContentPane().add(background, java.awt.BorderLayout.CENTER);

      jMenu1.setText("Archivo");

      Abrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
      Abrir.setText("Abrir");
      Abrir.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            AbrirActionPerformed(evt);
         }
      });
      jMenu1.add(Abrir);

      GuardarCambios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
      GuardarCambios.setText("Guardar Cambios");
      GuardarCambios.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            GuardarCambiosActionPerformed(evt);
         }
      });
      jMenu1.add(GuardarCambios);

      Salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
      Salir.setText("Salir");
      Salir.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            SalirActionPerformed(evt);
         }
      });
      jMenu1.add(Salir);

      jMenuBar1.add(jMenu1);

      setJMenuBar(jMenuBar1);

      pack();
   }// </editor-fold>//GEN-END:initComponents

  private void AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirActionPerformed
	  // TODO add your handling code here:
	  JFileChooser fileChooser = new JFileChooser();
	  int seleccion = fileChooser.showOpenDialog(this);

	  if (seleccion == JFileChooser.APPROVE_OPTION) {
		  rutaArchivo = fileChooser.getSelectedFile().getAbsolutePath();
		  String reglasLeidas = lectura.leerReglas(rutaArchivo);

		  if (reglasLeidas != null) {
			  jtaReglas.setText(reglasLeidas);
		  } else {
			  JOptionPane.showMessageDialog(this, "No se pudo leer el archivo seleccionado", "Error", JOptionPane.ERROR_MESSAGE);
		  }
	  }
  }//GEN-LAST:event_AbrirActionPerformed

   private void btnDerivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerivarActionPerformed
		if (!jtfCadena.getText().isBlank()) {
			if (!jtaReglas.getText().isBlank()) {
				reglas = lectura.obtenerReglas(jtaReglas.getText());
				tamMaxCabeza = reglas.get(0).cabeza.length();

				for (int i = 1; i < reglas.size(); i++) {
					if (tamMaxCabeza < reglas.get(i).cabeza.length()) {
						tamMaxCabeza = reglas.get(i).cabeza.length();
					}
				}

				soluciones.clear();

				String mensaje;
				String result;

				if (jrbIzq.isSelected()) {
					JOptionPane.showMessageDialog(this, "Iniciando derivacion por la IZQUIERDA", "Inicio", JOptionPane.INFORMATION_MESSAGE);
					derivacion.derivacionIzquierda(reglas.get(0).cabeza + "", jtfCadena.getText(), "", soluciones, reglas, tamMaxCabeza);
					mensaje = "Numero de derivaciones por la IZQUIERDA: " + soluciones.size();
					result = "RESULTADOS DE LA DERIVACION POR LA IZQUIERDA\n";
				} else {
					JOptionPane.showMessageDialog(this, "Iniciando derivacion por la DERECHA", "Inicio", JOptionPane.INFORMATION_MESSAGE);
					derivacion.derivacionDerecha(reglas.get(0).cabeza + "", jtfCadena.getText(), "", soluciones, reglas, tamMaxCabeza);
					mensaje = "Numero de derivaciones por la DERECHA: " + soluciones.size();
					result = "RESULTADOS DE LA DERIVACION POR LA DERECHA\n";
				}

				for (int i = 0; i < soluciones.size(); i++) {
					result += "\n" + soluciones.get(i);
				}

				switch (soluciones.size()) {
					case 0:
						result += "\n*************** La cadena no pertenece a la gramatica ***************";
						break;
					case 1:
						result += "\n\n" + mensaje + "\n***** La gramatica no es ambigua *****";
						break;
					default:
						result += "\n\n" + mensaje + "\n***** La gramatica es ambigua *****";
				}

				jtaResultado.setText(result);
			} else {
				JOptionPane.showMessageDialog(this, "Favor de ingresar o cargar las reglas de la gramatica", "Atención", JOptionPane.WARNING_MESSAGE);
			}
		} else {
			JOptionPane.showMessageDialog(this, "Favor de ingresar la cadena a derivar", "Atención", JOptionPane.WARNING_MESSAGE);
		}
   }//GEN-LAST:event_btnDerivarActionPerformed

   private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
		// TODO add your handling code here:
		this.dispose();
   }//GEN-LAST:event_SalirActionPerformed

   private void GuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarCambiosActionPerformed
		if (rutaArchivo != null) {
			FileWriter fichero = null;
			PrintWriter pw = null;

			try {
				fichero = new FileWriter(rutaArchivo);
				pw = new PrintWriter(fichero);
				pw.print(jtaReglas.getText());
				
				pw.close();
				fichero.close();
				
				JOptionPane.showMessageDialog(this, "Los cambios se guardaron correctamente", "Cambios guardados", JOptionPane.INFORMATION_MESSAGE);
			} catch (Exception e) {
				JOptionPane.showMessageDialog(this, "No es posible guardar los cambios", "Error", JOptionPane.ERROR_MESSAGE);
			}
		} else {
			JOptionPane.showMessageDialog(this, "Usted no abrió un Archivo", "Atención", JOptionPane.WARNING_MESSAGE);
		}
   }//GEN-LAST:event_GuardarCambiosActionPerformed

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JMenuItem Abrir;
   private javax.swing.JMenuItem GuardarCambios;
   private javax.swing.JMenuItem Salir;
   private javax.swing.JPanel background;
   private javax.swing.JButton btnDerivar;
   private javax.swing.ButtonGroup buttonGroup1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JMenu jMenu1;
   private javax.swing.JMenuBar jMenuBar1;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel10;
   private javax.swing.JPanel jPanel11;
   private javax.swing.JPanel jPanel12;
   private javax.swing.JPanel jPanel13;
   private javax.swing.JPanel jPanel14;
   private javax.swing.JPanel jPanel15;
   private javax.swing.JPanel jPanel16;
   private javax.swing.JPanel jPanel17;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JPanel jPanel4;
   private javax.swing.JPanel jPanel5;
   private javax.swing.JPanel jPanel6;
   private javax.swing.JPanel jPanel7;
   private javax.swing.JPanel jPanel8;
   private javax.swing.JPanel jPanel9;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JRadioButton jrbDer;
   private javax.swing.JRadioButton jrbIzq;
   private javax.swing.JTextArea jtaReglas;
   private javax.swing.JTextArea jtaResultado;
   private javax.swing.JTextField jtfCadena;
   // End of variables declaration//GEN-END:variables
}
